### ISSUE TITLE
Option to record function module interfaces

### ISSUE THREAD

**Issue by bunysae** [germanysources/regression_test#1]
Is there an option to record remote function module interfaces?
This would be quite handy for build an ramework like [WireMock](https://github.com/tomakehurst/wiremock) for remote function calls with sapjco or sapnco.

**Comment by germanysources** [comment]
I try to add this feature. I seems to be possible with using function module `FUNCTION_IMPORT_DOKU`

**Comment by germanysources** [comment]
The new clas `zdbgl_signature_record` contains utility functions for record function module signatures. You could use it to export the parameter values and their declaration to json. The corresponding debugger script is named `zdbgl_script_rec_signature`.
